# Generated by Django 5.1.3 on 2024-11-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleadoComp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfcemp', models.CharField(max_length=50)),
                ('nom_emp', models.CharField(max_length=100)),
                ('curp', models.CharField(max_length=18)),
                ('catemp', models.CharField(default='Sin categoría', max_length=50)),
            ],
        ),
    ]
