# Generated by Django 5.1.3 on 2024-11-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChequesB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfcemp', models.CharField(max_length=13, unique=True)),
                ('nom_emp', models.CharField(max_length=100)),
                ('curp', models.CharField(max_length=18)),
                ('catemp', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CHEQUES_B',
            },
        ),
    ]
