# Generated by Django 5.1.3 on 2024-11-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfc', '0002_alter_chequesb_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleadoComp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfcemp', models.CharField(max_length=13, unique=True)),
                ('nom_emp', models.CharField(max_length=100)),
                ('curp', models.CharField(max_length=18)),
                ('catemp', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'EMPLEADO_COMP',
            },
        ),
    ]
