# Generated by Django 5.1.3 on 2024-11-22 02:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfc', '0005_rename_nom_emp_empleadocomp_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleadocomp',
            old_name='nombre',
            new_name='nom_emp',
        ),
        migrations.RemoveField(
            model_name='empleadocomp',
            name='rfc',
        ),
        migrations.AddField(
            model_name='empleadocomp',
            name='catemp',
            field=models.CharField(default='Sin categoría', max_length=50),
        ),
        migrations.AddField(
            model_name='empleadocomp',
            name='rfcemp',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='empleadocomp',
            table=None,
        ),
    ]
