# Generated by Django 5.1.3 on 2024-11-20 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfc', '0005_rename_nom_emp_empleadocomp_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleadocomp',
            options={'managed': False},
        ),
    ]
