# Generated by Django 5.1.3 on 2024-11-21 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfc', '0006_alter_empleadocomp_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleadocomp',
            options={},
        ),
    ]
