# Generated by Django 5.1.3 on 2024-11-21 02:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfc', '0007_alter_empleadocomp_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleadocomp',
            name='curp',
        ),
        migrations.AddField(
            model_name='empleadocomp',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleadocomp',
            name='rfc',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterModelTable(
            name='empleadocomp',
            table=None,
        ),
    ]
