# Generated by Django 5.1.3 on 2024-11-09 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constancias', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Constancias',
            new_name='Constancia',
        ),
    ]
