# Generated by Django 5.1.3 on 2024-11-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constancias', '0003_configuracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='nombre',
            field=models.CharField(
                default='Configuracion global', max_length=100),
        ),
    ]
