# Generated by Django 5.1.3 on 2024-11-18 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constancias', '0004_configuracion_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='nombre',
        ),
    ]
