# Generated by Django 5.1.3 on 2024-11-25 23:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Constancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_constancia', models.CharField(choices=[('OTRO', 'Otro Motivo'), ('PROM_VERTICAL', 'Promoción Vertical'), ('ADMISION', 'Admisión'), ('HORAS_ADIC', 'Horas Adicionales'), ('CAMBIO_CENTRO', 'Cambios de Centro de Trabajo'), ('RECONOCIMIENTO', 'Reconocimiento'), ('PROM_HORIZONTAL', 'Promoción Horizontal'), ('BASE_ESTATAL', 'Basificación estatal'), ('CAMBIO_CENTRO_PREP', 'Cambios de Centro de Trabajo nivel preparatoria')], max_length=20)),
                ('Activa', models.BooleanField(default=True)),
                ('curp', models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(code='curp_invalido', message='La CURP no tiene un formato válido.', regex='^([A-Z][AEIOUX][A-Z]{2}\\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\\d|3[01])[HM](?:AS|B[CS]|C[CLMSH]|D[FG]|G[TR]|HG|JC|M[CNS]|N[ETL]|OC|PL|Q[TR]|S[PLR]|T[CSL]|VZ|YN|ZS)[B-DF-HJ-NP-TV-Z]{3}[A-Z\\d])(\\d)$')])),
                ('filiacion', models.CharField(max_length=13)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('categoria_plaza', models.CharField(max_length=100)),
                ('tipo_nombramiento', models.CharField(choices=[('09', 'Alta inicial'), ('10', 'Alta definitiva'), ('20', 'Alta interina limitada'), ('24', 'Alta en gravidez'), ('25', 'Alta en pensión'), ('95', 'Alta provisional'), ('96', 'Alta de confianza'), ('99', 'Alta provisional')], max_length=2)),
                ('clave_centro_trabajo', models.CharField(max_length=50)),
                ('nombre_centro_trabajo', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('sueldo_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('partida', models.CharField(blank=True, choices=[('7-1103', 'Código 7-1103'), ('14-1204', 'Código 14-1204'), ('15-1205', 'Código 15-1205')], max_length=10, null=True)),
                ('fecha_input', models.DateField()),
                ('motivo_constancia', models.TextField()),
                ('firma', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('incluir_logo', models.BooleanField(default=False)),
                ('comentarios_observaciones', models.TextField(blank=True, null=True)),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
                ('fecha_creacion_constancia', models.DateField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClavesConstancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=255)),
                ('constancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claves', to='agregar_constancia.constancia')),
            ],
        ),
        migrations.CreateModel(
            name='ContratoConstancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adscripcion', models.CharField(max_length=20, verbose_name='Clave de Centro de Trabajo')),
                ('clave_categoria', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_termino', models.DateField(verbose_name='Fecha de Término')),
                ('constancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='agregar_constancia.constancia')),
            ],
            options={
                'verbose_name_plural': 'Contratos constancia',
            },
        ),
        migrations.CreateModel(
            name='LicenciaConstancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adscripcion', models.CharField(max_length=20, verbose_name='Clave de Centro de Trabajo')),
                ('clave_categoria', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_termino', models.DateField(verbose_name='Fecha de Término')),
                ('constancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to='agregar_constancia.constancia')),
            ],
            options={
                'verbose_name_plural': 'Licencias constancia',
            },
        ),
    ]
