# Generated by Django 5.1.3 on 2024-11-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregar_constancia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constancia',
            name='curp',
            field=models.CharField(max_length=18),
        ),
    ]
