# Generated by Django 5.1.3 on 2024-11-22 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregar_constancia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClavesConstancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=255)),
                ('constancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claves', to='agregar_constancia.constancia')),
            ],
        ),
        migrations.CreateModel(
            name='ContratoConstancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adscripcion', models.CharField(max_length=20, verbose_name='Clave de Centro de Trabajo')),
                ('clave_categoria', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_termino', models.DateField(verbose_name='Fecha de Término')),
                ('constancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='agregar_constancia.constancia')),
            ],
            options={
                'verbose_name_plural': 'Contratos constancia',
            },
        ),
        migrations.CreateModel(
            name='LicenciaConstancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adscripcion', models.CharField(max_length=20, verbose_name='Clave de Centro de Trabajo')),
                ('clave_categoria', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_termino', models.DateField(verbose_name='Fecha de Término')),
                ('constancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to='agregar_constancia.constancia')),
            ],
            options={
                'verbose_name_plural': 'Licencias constancia',
            },
        ),
    ]
