# Generated by Django 5.1.3 on 2024-12-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregar_constancia', '0002_alter_constancia_curp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstanciaAccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constancia_type', models.CharField(max_length=50, unique=True)),
                ('is_enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
