# Generated by Django 5.1.3 on 2024-12-01 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agregar_constancia', '0003_constanciaaccesscontrol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constanciaaccesscontrol',
            old_name='is_enabled',
            new_name='habilitado',
        ),
        migrations.RenameField(
            model_name='constanciaaccesscontrol',
            old_name='constancia_type',
            new_name='tipo_constancia',
        ),
    ]
