version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: constanciasApp
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - ./app:/app

    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_USER_ADMIN: ${DB_USER_ADMIN}

      DB_NAME2: ${DB_NAME2}
      DB_USER2: ${DB_USER2}
      DB_PASSWORD2: ${DB_PASSWORD2}
      DB_ROOT_PASSWORD2: ${DB_ROOT_PASSWORD2}
      DB_USER_ADMIN2: ${DB_USER_ADMIN2}
      DB_HOST2: ${DB_HOST2}

      DB_NAME3: ${DB_NAME3}
      DB_USER3: ${DB_USER3}
      DB_PASSWORD3: ${DB_PASSWORD3}
      DB_ROOT_PASSWORD3: ${DB_ROOT_PASSWORD3}
      DB_USER_ADMIN3: ${DB_USER_ADMIN3}
      DB_HOST3: ${DB_HOST3}


      DB_HOST: ${DB_HOST}
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}

  db:
    image: mariadb
    container_name: constancias
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    ports:
      - 127.0.0.1:3310:3306

volumes:
  db: