# Generated by Django 5.1 on 2024-11-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtros', '0002_constancia_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constancia',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
