# Generated by Django 5.1 on 2024-11-09 20:41

import filtros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtros', '0005_remove_constancia_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constancia',
            name='nombre',
            field=models.CharField(max_length=255, validators=[filtros.models.validar_longitud_minima]),
        ),
    ]
