# Generated by Django 5.1.3 on 2024-11-15 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfc', '0004_delete_chequesb_alter_empleadocomp_rfcemp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleadocomp',
            old_name='nom_emp',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='empleadocomp',
            old_name='rfcemp',
            new_name='rfc',
        ),
        migrations.RemoveField(
            model_name='empleadocomp',
            name='catemp',
        ),
    ]
